Add fatal() function in run and runwin and use it properly if linking fails.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,4 +1,9 @@
 #!/bin/bash
+function fail {
+	echo "$1"
+	exit 1
+}
+
 if [ "$MAXPARALLEL" = "" ]; then
 	MAXPARALLEL="25"
 fi
@@ -26,16 +31,16 @@ if [ "$1" = "-boot" -o "$1" = "" ]; then
 	echo "Booting IRC server..."
 	killall -9 valgrind valgrind.bin memcheck memcheck-amd64-linux memcheck-x86-linux ircd unrealircd val 1>/dev/null 2>&1
 	sleep 1
-	cp -av ircdconfig/* ~/unrealircd/conf/ || exit 1
+	cp -av ircdconfig/* ~/unrealircd/conf/ || fail "Failed to copy ircdconfig"
 	cd ~/unrealircd/ || exit 1
 	mv data/tkl.db data/tkl.db.$$ 1>/dev/null 2>&1
 	mv data/channeldb.db data/channel.db.$$ 1>/dev/null 2>&1
-	bin/unrealircd -f irc2.conf || exit 1
-	bin/unrealircd -f irc1.conf || exit 1
-	bin/unrealircd -f irc3.conf || exit 1
+	bin/unrealircd -f irc2.conf || fail "UnrealIRCd failed to start (irc2)"
+	bin/unrealircd -f irc1.conf || fail "UnrealIRCd failed to start (irc1)"
+	bin/unrealircd -f irc3.conf || fail "UnrealIRCd failed to start (irc3)"
 	cd -
 	
-	timeout --kill-after=5 --signal=INT 10 tests/_pre_test || (echo "Linking failed"; exit 1)
+	timeout --kill-after=5 --signal=INT 10 tests/_pre_test || fail "Linking servers failed"
 	echo
 fi
 
diff --git a/runwin b/runwin
--- a/runwin
+++ b/runwin
@@ -1,4 +1,12 @@
 #!/bin/bash
+function fail {
+	echo "FATAL ERROR: $1"
+	echo "Cleaning up..."
+	taskkill -im unrealircd.exe -f
+	echo "Tests failed. See errors above."
+	exit 1
+}
+
 if [ "$MAXPARALLEL" = "" ]; then
 	MAXPARALLEL="25"
 fi
@@ -30,8 +38,8 @@ if [ "$1" = "-boot" -o "$1" = "" ]; then
 	echo "Booting IRC server..."
 	taskkill -im unrealircd.exe -f
 	sleep 1
-	cp -av ircdconfig/* "$UNREALIRCDDIR/conf/" || exit 1
-	cd "$UNREALIRCDDIR/bin" || exit 1
+	cp -av ircdconfig/* "$UNREALIRCDDIR/conf/" || fail "Could not copy configuration files"
+	cd "$UNREALIRCDDIR/bin" || fail "Could not change to UnrealIRCd directory"
 	echo "Now in:"
 	pwd
 	./unrealircd -f irc2.conf&
@@ -40,7 +48,7 @@ if [ "$1" = "-boot" -o "$1" = "" ]; then
 	sleep 10
 	cd -
 	
-	timeout --kill-after=5 --signal=INT 10 tests/_pre_test || (echo "Linking failed"; exit 1)
+	timeout --kill-after=5 --signal=INT 10 tests/_pre_test || fail "UnrealIRCd servers did not link"
 	echo
 fi
 
@@ -110,6 +118,5 @@ fi
 cd - 1>/dev/null 2>&1
 
 taskkill -im unrealircd.exe -f
-rem taskkill -im python.exe -f
 
 exit $failed
